title: Security in Machine Learning and its Applications (SiMLA 2023)
url: "simla-workshop.github.io/Simla2023"
baseur1: "/Simla2023"

markdown: kramdown
# ins_logo: "images/simla-logo.png"

tracking_id: #

footer: yes
footer_url: "https://sulab-sever.u-aizu.ac.jp/ACNS2023/"
footer_text: "SiMLA 2023 (Co-located with ACNS2023)"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "ACNS 2023"
   link: "https://sulab-sever.u-aizu.ac.jp/ACNS2023/"

