title: Call for papers
url: ""
baseur1: "/Simla2024"

markdown: GFM
# ins_logo: "images/simla-logo.png"

tracking_id: #

footer: yes
footer_url: "https://wp.nyu.edu/acns2024/"
footer_text: "SiMLA 2024 (Co-located with ACNS2024)"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "ACNS 2024"
   link: "https://wp.nyu.edu/acns2024/"

