title: Security in Machine Learning and its Applications (SiMLA 2022) TEMPLATE
url: ""
baseurl: "/simla2022"

markdown: kramdown
# ins_logo: "images/simla-logo.png"

tracking_id: #

footer: yes
footer_url: "https://sites.google.com/di.uniroma1.it/acns2022/"
footer_text: "SiMLA 2022 (Co-located with ACNS2022)"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "ACNS 2022"
   link: "https://sites.google.com/di.uniroma1.it/acns2022/"

