title: Security in Machine Learning and its Applications (SiMLA 2023)
url: ""
baseurl: ""

markdown: kramdown
# ins_logo: "images/simla-logo.png"

tracking_id: #

footer: yes
footer_url: "https://sites.google.com/di.uniroma1.it/acns2023/"
footer_text: "SiMLA 2023 (Co-located with ACNS2023)"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "ACNS 2023"
   link: ""

