title: Security in Machine Learning and its Applications (SiMLA 2025)
url: ""
baseur1: "/Simla2025"

markdown: GFM
# ins_logo: "images/simla-logo.png"

tracking_id: #

footer: yes
footer_url: "https://wp.nyu.edu/acns2025/"
footer_text: "SiMLA 2025 (Co-located with ACNS2025)"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "ACNS 2025"
   link: "https://wp.nyu.edu/acns2025/"

